/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;

import backend.DrawingEngine;
import backend.Line;
import backend.Shape;
import backend.Circle;
import java.awt.Graphics;
import java.util.ArrayList;

/**
 *
 * @author LENOVO
 */
public class DrawingArea extends javax.swing.JPanel implements DrawingEngine{

    
    ArrayList<Shape> drawnShapes = new ArrayList<>();
    int index = 0;
    
    /**
     * Creates new form DrawingArea
     */
    public DrawingArea() {
        initComponents();
    }
    
    @Override
     public void addShape(Shape shape) {
        drawnShapes.add(shape);
    }

    @Override
    public void removeShape(Shape shape) {
       for(int i = 0 ; i<drawnShapes.size();i++)
       {
           if(drawnShapes.get(i).equals(shape))
               drawnShapes.remove(drawnShapes.get(i));
       }
    }

    
    @Override
    public Shape[] getShapes() {
        Shape[] shapeArray = new Shape[drawnShapes.size()];
        return  drawnShapes.toArray(shapeArray);
    }

    @Override
    public void refresh(Graphics canvas) {
       this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); 
        for(int i =0; i < drawnShapes.size();i++)
        {
            drawnShapes.get(i).draw(g);
        }
            
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
